- name: Deploy Nginx container
  hosts: ubuntu
  become: true
  tasks:
    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
